version: '3.8'

services:
  # MySQL数据库
  mysql:
    image: mysql:8.0
    container_name: seckill-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: seckill_test
      MYSQL_USER: seckill
      MYSQL_PASSWORD: seckill123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/main/resources/db:/docker-entrypoint-initdb.d
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password
    networks:
      - seckill-network

  # Redis缓存
  redis:
    image: redis:7.2-alpine
    container_name: seckill-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - seckill-network

  # RabbitMQ消息队列
  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: seckill-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"   # AMQP端口
      - "15672:15672" # 管理界面端口
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - seckill-network

  # 可选：添加Redis管理界面
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: seckill-redis-ui
    environment:
      REDIS_HOSTS: redis:seckill-redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - seckill-network

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
  rabbitmq_data:
    driver: local

networks:
  seckill-network:
    driver: bridge
